databases:
  - name: valorantdb
    plan: free
    databaseName: valorant
    user: valorant

services:
  - type: web
    plan: free
    name: valorant-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn valorant_project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: valorantdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
